### ISSUE TITLE
Kadenze Course Content is Freely Accessible

### ISSUE THREAD

**Issue by mynock** [astorfi/TensorFlow-Roadmap#2]
Great list of resources! The only thing I'd like to point out is that the "Creative Applications of Deep Learning with TensorFlow" course on Kadenze is actually a free course. There are additional features of the platform you can use if you upgrade to a paid account, but the content and instructional material of the course itself are completely free.

Thanks!

**Comment by astorfi** [comment]
@mynock Thank you so much for your feedback. It would be great if you can create a pull request and add the resource to this repository in one of the categories that you think it's a suitable fit!
